### ISSUE TITLE
WebDriverException

### ISSUE THREAD

**Issue by bhargavpanth** [DanMcInerney/search-google#4]
My browser got updated to FireFox 47 and I'v been facing this problem ever since. Is there no way to resolve this without rolling back to older version of FF?

raise WebDriverException("The browser appears to have exited "
selenium.common.exceptions.WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.

**Comment by matkoniecz** [comment]
For what it is worth - everything works for me with Firefox 61.

**Comment by matkoniecz** [comment]
Also, is Selenium really relying on a system browser?

**Comment by MShel** [comment]
it depends on the platform you running on, for firefox can specify binary you want to use in constructor see https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/firefox/webdriver.py

**Comment by mehmetcanbudak** [comment]
I have a similar problem it seems.

I get this error.

Traceback (most recent call last):
  File "search-google.py", line 81, in <module>
    main()
  File "search-google.py", line 60, in main
    br = start_browser()
  File "search-google.py", line 23, in start_browser
    br = webdriver.Firefox()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 80, in __init__
    self.binary, timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/firefox/extension_connection.py", line 52, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 108, in _wait_until_connectable
    % (self.profile.path))
selenium.common.exceptions.WebDriverException: Message: Can't load the profile. Profile Dir: /var/folders/nl/c4hxb7h51qj9_yc726n_19zm0000gn/T/tmpPvRyeN If you specified a log_file in the FirefoxBinary constructor, check it for details.
